name             'freedomserver'
maintainer       'anthony de silva'
maintainer_email 'anthony@iamfree.com'
license          'All rights reserved'
description      'Installs/Configures freedomserver'
long_description 'Installs/Configures freedomserver'
version          '0.1.0'
